### ISSUE TITLE
Update/write server piece to dynamically allocate ports for pods.

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ha-addons#3]
Update ssh add-on so that first time it connects it queries a serverless endpoint that gets the first available port block at 10000 to use for tunneling with this pod.

Endpoint will return port block to use, given a Pod ID.  Endpoint will update the DDB table for pods w/ Port block.

Endpoint looks up pod id to see if it already has a port assigned, if not, then looks for available port, updates DDB and returns via API.

**Comment by godslave05** [comment]
Depends on @godslave05

**Comment by olagalal** [comment]
in progress

**Comment by olagalal** [comment]
@scottdear Are we going to have a DELETE endpoint to remove disconnected pods? or they should be reserved for them even if they disconnect, maybe they will reconnect in future?

**Comment by olagalal** [comment]
I'm blocked by:
access to HA

**Comment by scottdear** [comment]
@Mikisson needs to update angela@oceanbuilders.io email (also scott would be cool), then @angiedear needs to update Nabu Casa configuration so that @olagalal can get in for testing.

**Comment by omerll** [comment]
In progress

**Comment by olagalal** [comment]
The issue is done. The next step is to check if the ports is used or not, so we can locate the next available port, which is related to this issue #4
