### ISSUE TITLE
Update ssh tunnel add on so it communicates w/ the admin server endpoints

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/ha-addons#4]
Update this so it contacts the remote admin server and 1 gets a list of pods and finds an available starting port.
If pod does not exist it will post to the pods endpoint to add a new pod to the table w/ the proper ports.  If the pod does exist the plugin will use the defined ports for the conneciton.

**Comment by omerll** [comment]
In progress, (Related to the other issue)

**Comment by olagalal** [comment]
in testing phase

**Comment by olagalal** [comment]
Should we have 'DELETE request' when the seapod disconnects?

**Comment by scottdear** [comment]
I don't think we need a delete at this point.
2 points

**Comment by olagalal** [comment]
blocked by: I need the POST request.

**Comment by omerll** [comment]
Waiting on Asad
Blocking on issue #35
https://github.com/oceanbuilders/smartpod/issues/35

**Comment by angiedear** [comment]
add testing and pull request. @godslave05 delete old data 
additional 2 points

**Comment by angiedear** [comment]
In progress no blockers

**Comment by angiedear** [comment]
In progress no blockers

**Comment by olagalal** [comment]
done and created a PR.

**Comment by diegopau** [comment]
@olagalal @angiedear can we get more documentation on this? I created a page for it here https://wiki.oceanbuilders.com/books/development-documentation/page/ssh-tunnel-add-on-registering-new-pods-with-the-admin-web-server could you edit it and document:
- The need of the SSH tunneling (briefly)
- How a pod is registered and how it is assigned a port
- What happens if a pod has the same name as an existing one
- How are the SSH keys handled? (I think in the call you mentioned something about manually copying it so AWS, so how will this be automated?)

We agreed in a previous calls that all issues that have some work done will go through the "Documentation" column before being closed.

**Comment by angiedear** [comment]
@diegopau we did a design doc prior to implementing the adding of doc to the wiki.  @olagalal we need to locate that document and put it in the wiki please :)

**Comment by olagalal** [comment]
@diegopau @angiedear on it 🙌🏼

**Comment by scottdear** [comment]
@olagalal did a detailed design document, and there is also a diagram
that answers most of these questions.  Should we open a doc story to
clean it up and add the missing bits to the Wiki.  Or should we move
this to the doc column and add any needed extra points?

I'll try to answer your questions below (briefly).

As for 1) Omer can tell you about that one.  It prevents us having to
expose the POD on the internet.  The POD is only accessed via our AWS
instance and the ssh tunnel from the POD to the AWS instance.  Omer
opened up a port on the instance in his shop and he was immediately hit
by all kinds of hosts on the Internet trying to brute force into his
Pi.  Long story short, it allows us to remote access the POD's w/ a high
level of security.

2)  Pod info is stored in DynamoDB, the DB is scanned for the next
available port and it's assigned to the POD.  We probably should store a
"Next POD" or index the port number field so it's a more efficient
lookup, but that won't be an issue until we get into more than a
thousand or so pods.

3) Right now the port numbers are assigned in blocks of 10, starting at
10000, so pod 1 gets 10000-10009, and pod 2 gets 10010-100019, etc.  It
uses 2 of them currently for ssh tunnel and http tunnel into the HASS
instance.  There are 8 ports reserved for future services that we might
need to tunnel from the AWS instance to the PODS.  When a number is
assigned a lookup is done, in DynamoDB to validate that the port range
is not in use by another pod.

4) Right now ssh key provisioning is manual.  We have an open story to
add that functionality to the provisioning process.  It requires the
generation of a private key on the POD and a public key to be handed off
and stored on the AWS instance.  Part of the story for this is to figure
out the design, off the top I say it will be an endpoint where the
public key is POST'd that's authenticated by cognito.  We'll want to use
some validated parameter from Cognito to make sure the authenticated
user is authorized to add a POD via the endpoint which brings me to the
last part of this.

5) We need to write an authorizer lambda so that any endpoint we have
will bounce off of the Cognito hosted UI and user the same
usernames/passwords that we're currently using for the Wiki, etc.

and

6) We need to add the Cognito integration into Hass and test it.  That
means someone can sign in once and they can get into the Wiki, The Admin
UI (If Authorized), and the Home Assistant UI (If the authenticated user
is authorized for that particular pod) with their Cognito Username and
password, only having to log in once.

**Comment by angiedear** [comment]
1 point

**Comment by diegopau** [comment]
Is this the detailed design document https://docs.google.com/document/d/1PcjlqMTXRr1cYu-H9bS_d1metAvZthLJJl51ZVmGm_4/edit ?

Thank you for your answers Scott.

@olagalal let us know if you want to add anything, else I will take care of updating the wiki with Scott's information and close the issue.

**Comment by diegopau** [comment]
Thank you @olagalal
